include: package:flutter_lints/flutter.yaml

linter:
  rules: # https://dart.dev/tools/linter-rules
    prefer_single_quotes: true
    prefer_relative_imports: true
    directives_ordering: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    avoid_redundant_argument_values: true
