name: assets_app
description: "A Tree View Application that shows companies Assets."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  freezed: ^2.5.2
  go_router: ^14.2.0
  intl: ^0.19.0
  intl_utils: ^2.8.7
  json_annotation: ^4.9.0
  retrofit: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_intl:
  enabled: true
  output_dir: "lib/l10n/generated"
